<?php

/**
 * @file
 * Adds the enquire.js library to the website.
 *
 * Implements hook_init().
 */
function enquirejs_init() {
  $lib = enquirejs_get_library();
  if ($lib) {
    // Add library to all pages.
    drupal_add_js($lib);
  }
}

/**
 * Wrapper to get the library so it works with install profiles.
 */
function enquirejs_get_library($file = 'enquire.js') {
  // Account for libraries not being available on install.
  if (function_exists('libraries_get_libraries')) {
    $libraries = libraries_get_libraries();
    if (isset($libraries['enquirejs'])) {
      return $libraries['enquirejs'] . '/' . $file;
    }
  }
  else {
    $directory = 'libraries';
    $profile = drupal_get_profile();
    $config = conf_path();
    $lib = 'enquirejs/' . $file;
    // Look in install profile.
    if (file_exists("profiles/$profile/$directory/$lib")) {
      return "profiles/$profile/$directory/$lib";
    }
    // Look in sites all.
    // Always search sites/all/*.
    if (file_exists("sites/all/$directory/$lib")) {
      return "sites/all/$directory/$lib";
    }
    // Look in a local domain as last resort.
    // Also search sites/<domain>/*.
    if (file_exists("$config/$directory/$lib")) {
      return "$config/$directory/$lib";
    }
  }
  return FALSE;
}
