<?php
$plugin = array(
  'title'     => t('Email Template'),
  'theme'     => 'baseline_email_template',
  'icon'      => 'baseline_email_template.png',
  'admin css' => 'baseline_email_template.css',
  'category'  => 'Baseline Panels Everywhere',
  'regions' => array(
    'content'           => t('Main content'),
    'secondary_content' => t('Secondary'),
    'tertiary_content'  => t('Tertiary'),
    'footer'            => t('Footer'),
    'leaderboard'       => t('Leaderboard'),
    'header'            => t('Header'),
    'menu_bar'          => t('Menu Bar'),
    'help'              => t('Help'),
  ),
);
