<?php
$plugin = array(
  'title'     => t('Baseline Panels Everywhere site template'),
  'theme'     => 'baseline_site_template',
  'icon'      => 'baseline_site_template.png',
  'admin css' => 'baseline_site_template.css',
  'category'  => 'Baseline Panels Everywhere',
  'regions' => array(
    'sidebar_first'     => t('Sidebar first'),
    'sidebar_second'    => t('Sidebar second'),
    'content'           => t('Main content'),
    'highlighted'       => t('Highlighted'),
    'content_aside'     => t('Aside'),
    'secondary_content' => t('Secondary'),
    'tertiary_content'  => t('Tertiary'),
    'footer'            => t('Footer'),
    'leaderboard'       => t('Leaderboard'),
    'header'            => t('Header'),
    'menu_bar'          => t('Menu Bar'),
    'help'              => t('Help'),
  ),
);
